services:
  api:
    build: .
    ports:
      - "50007:50007"
    environment:
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST:-localhost}
      - ELASTICSEARCH_PORT=${ELASTICSEARCH_PORT:-9200}
      - REDIS_HOST=${REDIS_HOST:-localhost}
      - REDIS_PORT=${REDIS_PORT:-6379}
    network_mode: "host"  # This allows connecting to remote services
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:50007/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Optional Redis service - comment out if using remote Redis
  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: unless-stopped

volumes:
  redis_data: